default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  database: stubs
  username: root
  password: auto@123
  host: localhost
  encoding: utf8
test:
  adapter: mysql
  database: stubs
  username: root
  password: auto@123
  host: localhost
  encoding: utf8
production:
  adapter: mysql
  database: stubs
  username: root
  password: auto@123
  host: localhost
  encoding: utf8
